GET http://127.0.0.1:3002

###
GET http://127.0.0.1:3002/obtenerPokemones

###
POST http://127.0.0.1:3002/agregarPokemon
Content-Type: application/json

{
  "nombre": "Lapras",
  "tipo": [
    "Agua",
    "Hielo"
  ],
  "habilidades": [
    "Absorber Agua",
    "Caparazón",
    "Hidratación",
    null
  ]
}

###
GET http://127.0.0.1:3002/obtenerPokemonesPorTipo/dragon

###
GET http://127.0.0.1:3002/obtenerPokemonesPorTipo/agua

###
GET http://127.0.0.1:3002/usarPokemon/Lapras